name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main # Change to master if your default branch is named master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-python: '3.11'

      - name: Install Dependencies
        run: |
          pip install sphinx sphinx-rtd-theme # Add any other documentation themes/plugins here

      - name: Build HTML Docs
        run: |
          sphinx-build -b html docs/source docs/build/html # Adjust path to your source and build folders

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
